### ISSUE TITLE
sch:extends without a @href fails

### ISSUE THREAD

**Issue by cmarchand** [mricaud/xml-utilities#18]
`sch:extends` are not supported if `@href` is not present. And schematron specification allows missing `@href` if a previous `<sch:include` has been set and imports the referenced `sch:extends/@id`.

This has to be corrected there : https://github.com/mricaud/xml-utilities/blob/master/src/main/xsl/org/mricaud/xml-utilities/get-xml-file-static-dependency-tree.xsl#L288

**Comment by mricaud** [comment]
Thank you @cmarchand
